version: "3.0"

services:
  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./frontend:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && yarn start"
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

#   db:
#     image: mysql:8.0
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_DATABASE: test
#       MYSQL_USER: user
#       MYSQL_PASSWORD: user
#       MYSQL_ROOT_PASSWORD: root
#       TZ: 'Asia/Tokyo'
#     volumes:
#       - mysql-volume:/var/lib/mysql
#       - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

# volumes:
#   mysql-volume: